/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import keeptoo.Drag;

/**
 *
 * @author SUBZERO FT. Miraz Hossain (miraz4300@gmail.com)
 */
public class T2Instance extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
	ResultSet rs = null;
        public static String WelcomeName = "";

    /**
     * Creates new form SignUp
     */
    public T2Instance() {
        initComponents();
        conn = SQLConnection.ConnecrDb();
        clock();
        clock2();
        centerize();
    }
    
    
    
    
     public void centerize() {
		Dimension screenSize, frameSize;
		int x, y;
		screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		frameSize = getSize();
		x = (screenSize.width - frameSize.width) / 2;
		y = (screenSize.height - frameSize.height) / 2;
		setLocation(x, y);
	}
    
    
    
    
    
    private void login() {
		try {
			String query = "SELECT * FROM EMPLOYEE WHERE E_Username = ? And E_Password = ?";
			pst = (PreparedStatement) conn.prepareStatement(query);
			pst.setString(1, usernameField.getText());
			pst.setString(2, passField.getText());
			
			rs = pst.executeQuery();
			
			//int count = 0;
			if(rs.next()) {
                            WelcomeName = rs.getString("E_Name");
				JOptionPane.showMessageDialog(null, "Login Success");
				Management m = new Management();
				m.setVisible(true);
				dispose();
			}
			else {
				JOptionPane.showMessageDialog(null, "Login Failed");
			}
			
			pst.close();
			rs.close();
			
		}
		catch(Exception e) {
			
			e.printStackTrace();
			
		}
	}
    
    
    
    
    private void clock() {
		Thread clock = new Thread() {
			public void run() {
				try {
					for (;;) {
						Calendar cal = new GregorianCalendar();
						SimpleDateFormat formatter = new SimpleDateFormat("hh:");
						java.util.Date date = cal.getTime();
						String timeString = formatter.format(date);
						hourLabel.setText(timeString);
						sleep(1000);
					}
                                        
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		};
		clock.start();
	}
  
    
    
    
    
       private void clock2() {
		Thread clock = new Thread() {
			public void run() {
				try {
					for (;;) {
						Calendar cal = new GregorianCalendar();
						SimpleDateFormat formatter = new SimpleDateFormat("mm:ss a");
						java.util.Date date = cal.getTime();
						String timeString = formatter.format(date);
						minuteLabel.setText(timeString);
						sleep(1000);
					}
                                        
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		};
		clock.start();
	}
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        usernameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnApply = new keeptoo.KButton();
        btnSignup = new keeptoo.KButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hourLabel = new javax.swing.JLabel();
        minuteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkGradientFocus(-250);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        usernameField.setCaretColor(new java.awt.Color(255, 51, 255));
        usernameField.setOpaque(false);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 440, 30));

        passField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        passField.setCaretColor(new java.awt.Color(255, 0, 255));
        passField.setOpaque(false);
        kGradientPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 440, 30));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("username");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("password");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        btnApply.setText("LogIn");
        btnApply.setkBorderRadius(30);
        btnApply.setkEndColor(new java.awt.Color(245, 175, 25));
        btnApply.setkFillButton(false);
        btnApply.setkHoverEndColor(new java.awt.Color(51, 51, 255));
        btnApply.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btnApply.setkStartColor(new java.awt.Color(255, 255, 255));
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 170, 30));

        btnSignup.setText("Sign-Up");
        btnSignup.setkBorderRadius(30);
        btnSignup.setkEndColor(new java.awt.Color(245, 175, 25));
        btnSignup.setkHoverEndColor(new java.awt.Color(245, 175, 25));
        btnSignup.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btnSignup.setkHoverStartColor(new java.awt.Color(241, 39, 17));
        btnSignup.setkStartColor(new java.awt.Color(255, 102, 255));
        kGradientPanel1.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 160, 30));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("username");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("or");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, -1, -1));

        btn_exit.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(204, 204, 204));
        btn_exit.setText("X");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("T2microdata");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_user_male_circle_50px.png"))); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_fidget_spinner_filled_25px.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        hourLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        hourLabel.setForeground(new java.awt.Color(255, 255, 255));
        hourLabel.setText("Hour");
        kGradientPanel1.add(hourLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 70, 60));

        minuteLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        minuteLabel.setForeground(new java.awt.Color(255, 255, 255));
        minuteLabel.setText("minute");
        kGradientPanel1.add(minuteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 70, 20));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
        //drag
        
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
        // Drag Mouse
        new Drag(kGradientPanel1).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
        new Drag(kGradientPanel1).onPress(evt);
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
        if (usernameField.getText().equals("")) {
					JOptionPane.showMessageDialog(null, "Enter Username");
				} else if (passField.getText().equals("")) {
					JOptionPane.showMessageDialog(null, "Enter passward to continue");
				} else {
				login();
			}
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T2Instance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T2Instance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T2Instance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T2Instance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T2Instance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnApply;
    private keeptoo.KButton btnSignup;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel minuteLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
